// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
//
// Write proofs/agda/ExactCounts/Sweep.agda: a table of display roundings over a
// whole grid of inputs, for Agda to certify.
//
// This script is a convenience, not a source of truth.  Nothing it computes is
// trusted: Sweep.agda proves by `refl` that the table's inputs are exactly the
// grid and that every answer is `roundHalfAway`'s.  If this generator had a bug,
// the module would not type-check.
//
//   bun proofs/gen-sweep.js          write Sweep.agda
//   bun proofs/gen-sweep.js --check  fail if Sweep.agda differs from a fresh write

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PROOFS = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(PROOFS, "agda", "ExactCounts", "Sweep.agda");

// The grid.  Sweep.agda states the same bounds and proves the table covers them.
const N = 30;      // numerators -N .. N
const DENOMS = 16; // denominators 1 .. DENOMS, stored as d = denominator - 1
const DIGITS = 4;  // decimal places 0 .. DIGITS - 1

/**
 * Round n / D to s decimal places, halves away from zero, as a scaled integer m
 * representing m / 10^s. Expects BigInt inputs with D > 0n and s >= 0n.
 * Throws RangeError for a zero denominator or a negative precision.
 */
function roundHalfAway(n, D, s) {
  const a = n < 0n ? -n : n;
  const m = (2n * a * 10n ** s + D) / (2n * D);
  return n < 0n ? -m : m;
}

/** Write an integer as an Agda ℤ literal. */
function agdaInt(v) {
  return v < 0n ? `-[1+ ${-v - 1n} ]` : `+ ${v}`;
}

/** Render the whole module text. */
function render() {
  // One block per (precision, denominator).  A single list of thousands of
  // `∷` makes Agda's operator parser the bottleneck (97 s of 129 s, measured).
  const blocks = [];
  let rowCount = 0;
  for (let s = 0n; s < BigInt(DIGITS); s++) {
    for (let d = 0n; d < BigInt(DENOMS); d++) {
      const name = `block-${s}-${d}`;
      const rows = [];
      for (let n = -BigInt(N); n <= BigInt(N); n++) {
        rows.push(`  row (${agdaInt(n)}) ${d} ${s} (${agdaInt(roundHalfAway(n, d + 1n, s))}) ∷`);
      }
      rowCount += rows.length;
      blocks.push(`-- Precision ${s}, denominator ${d + 1n}.\n${name} : List Row\n${name} =\n${rows.join("\n")}\n  []`);
    }
  }
  const names = blocks.map((b) => b.match(/^(block-\S+) :/m)[1]);
  return `-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath) <j.d.a.jewell@open.ac.uk>
--
-- GENERATED by proofs/gen-sweep.js.  Do not edit the table by hand.
--
-- Display rounding over a whole grid: every numerator in -${N} .. ${N}, every
-- denominator in 1 .. ${DENOMS}, every precision in 0 .. ${DIGITS - 1} places.  That is
-- ${rowCount} rows, ties of both signs among them.
--
-- The table is not trusted.  Two \`refl\` proofs check it:
--   * \`sweep-covers-grid\`: its inputs are exactly \`grid\`, in order, so no
--     point is missing or repeated;
--   * \`sweep-agrees\`: every answer is \`roundHalfAway\`'s.
-- \`sweep-sound\` then makes every row an \`IsRoundHalfAway\` fact.  By
-- \`unique-halfAway\` it is the only correct answer for that input.
--
-- \`proofs/extract-vectors.js\` copies the rows to \`proofs/vectors/sweep.toml\`.
-- \`test/test_proof_vectors.jl\` checks the shipped Julia rounding on every row.

{-# OPTIONS --without-K --safe #-}

module ExactCounts.Sweep where

open import ExactCounts.DecimalRounding using (IsRoundHalfAway; roundHalfAway; roundHalfAway-sound)

open import Data.Bool.Base using (Bool; true; false; _∧_)
open import Data.Integer.Base using (ℤ; +_; -[1+_])
import Data.Integer.Properties as ℤₚ
open import Data.List.Base using (List; []; _∷_; map; concat; concatMap; reverse; upTo; _++_)
open import Data.List.Relation.Unary.All using (All; []; _∷_)
open import Data.Nat.Base using (ℕ)
open import Data.Product using (_×_; _,_)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; subst)
open import Relation.Nullary.Decidable using (⌊_⌋; yes; no)

-- One row: round numerator n over denominator d + 1 to s places, giving m.
record Row : Set where
  constructor row
  field
    n : ℤ
    d : ℕ
    s : ℕ
    m : ℤ

open Row

-- The input of a row, without its answer.
input : Row → ℤ × ℕ × ℕ
input r = n r , d r , s r

-- The grid, stated independently of the table: -${N} .. ${N} in increasing order.
numerators : List ℤ
numerators = map -[1+_] (reverse (upTo ${N})) ++ map +_ (upTo ${N + 1})

-- Every input, ordered by precision, then denominator, then numerator.
grid : List (ℤ × ℕ × ℕ)
grid = concatMap (λ s → concatMap (λ d → map (λ n → n , d , s) numerators) (upTo ${DENOMS})) (upTo ${DIGITS})

-- Whether a row's answer is the one \`roundHalfAway\` computes.
agrees : Row → Bool
agrees r = ⌊ roundHalfAway (n r) (d r) (s r) ℤₚ.≟ m r ⌋

-- Whether every row of a list agrees.
allAgree : List Row → Bool
allAgree []       = true
allAgree (r ∷ rs) = agrees r ∧ allAgree rs

-- A list on which \`allAgree\` holds is a list of correct roundings.
allAgree-sound : ∀ rs → allAgree rs ≡ true → All (λ r → IsRoundHalfAway (n r) (d r) (s r) (m r)) rs
allAgree-sound []       _ = []
allAgree-sound (r ∷ rs) h with roundHalfAway (n r) (d r) (s r) ℤₚ.≟ m r
... | yes p = subst (IsRoundHalfAway (n r) (d r) (s r)) p (roundHalfAway-sound (n r) (d r) (s r))
                 ∷ allAgree-sound rs h
... | no _  with h
... | ()

-- The table, block by block.

${blocks.join("\n\n")}

-- The whole table.
sweep : List Row
sweep = concat (${names.join(" ∷ ")} ∷ [])

-- The table covers the grid exactly.
sweep-covers-grid : map input sweep ≡ grid
sweep-covers-grid = refl

-- Every answer in the table is \`roundHalfAway\`'s.
sweep-agrees : allAgree sweep ≡ true
sweep-agrees = refl

-- So every row is a correct display rounding.
sweep-sound : All (λ r → IsRoundHalfAway (n r) (d r) (s r) (m r)) sweep
sweep-sound = allAgree-sound sweep sweep-agrees
`;
}

const text = render();
if (process.argv.includes("--check")) {
  if (!existsSync(OUTPUT) || readFileSync(OUTPUT, "utf8") !== text) {
    console.error("gen-sweep: Sweep.agda differs from a fresh generation; run `bun proofs/gen-sweep.js`");
    process.exit(1);
  }
  console.log("gen-sweep: Sweep.agda is current");
} else {
  writeFileSync(OUTPUT, text);
  console.log(`gen-sweep: wrote ${OUTPUT}`);
}
